runtime: python
env: flex
entrypoint: gunicorn -b :$PORT hello_project.wsgi

runtime_config:
  python_version: 3

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

manual_scaling:
  instances: 1
